name: interactive_maps_marker
description: Easy to use Animated Maps Markers with detail card. Use it for store or any place locator.
version: 0.0.1
maintainer: Atiq Samtia (@AtiqSamtia)
homepage: https://github.com/atiqsamtia/interactive_maps_marker_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.28+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/